services:
  postgres:
    image: postgres:16
    container_name: reliserv_postgres
    environment:
      POSTGRES_USER: reliserv
      POSTGRES_PASSWORD: reliserv
      POSTGRES_DB: reliserv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: reliserv_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
